import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoDir = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const localesDir = resolve(repoDir, "locales");
const outputFile = resolve(repoDir, "src/shared/generated/i18n-catalogs.js");
const DEFAULT_LOCALE = "zh-CN";
const checkOnly = process.argv.includes("--check");

const catalogs = await readCatalogs();
validateCatalogs(catalogs);

const output = [
  "// Generated by scripts/generate_i18n_catalogs.mjs. Do not edit by hand.",
  `export const DEFAULT_LOCALE = ${JSON.stringify(DEFAULT_LOCALE)};`,
  `export const SUPPORTED_LOCALES = ${JSON.stringify(Object.keys(catalogs), null, 2)};`,
  `export const I18N_CATALOGS = ${JSON.stringify(catalogs, null, 2)};`,
  "",
].join("\n");

if (checkOnly) {
  const current = await readFile(outputFile, "utf8").catch(() => "");
  if (current !== output) {
    throw new Error("Generated i18n catalog is out of date. Run `npm run i18n:generate`.");
  }
} else {
  await mkdir(dirname(outputFile), { recursive: true });
  await writeFile(outputFile, output);
}

async function readCatalogs() {
  const entries = await readdir(localesDir, { withFileTypes: true });
  const localeFiles = entries
    .filter((entry) => entry.isFile() && entry.name.endsWith(".json"))
    .map((entry) => entry.name)
    .sort((left, right) => {
      if (left === `${DEFAULT_LOCALE}.json`) {
        return -1;
      }
      if (right === `${DEFAULT_LOCALE}.json`) {
        return 1;
      }
      return left.localeCompare(right);
    });

  if (localeFiles.length === 0) {
    throw new Error("No locale JSON files found.");
  }

  const result = {};
  for (const fileName of localeFiles) {
    const locale = fileName.replace(/\.json$/u, "");
    const raw = await readFile(resolve(localesDir, fileName), "utf8");
    result[locale] = JSON.parse(raw);
  }

  if (!result[DEFAULT_LOCALE]) {
    throw new Error(`Missing default locale file: locales/${DEFAULT_LOCALE}.json`);
  }

  return result;
}

function validateCatalogs(catalogs) {
  const defaultLeaves = collectLeaves(catalogs[DEFAULT_LOCALE]);
  for (const [locale, catalog] of Object.entries(catalogs)) {
    const leaves = collectLeaves(catalog);
    validateKeySet(locale, defaultLeaves, leaves);
    validatePlaceholders(locale, defaultLeaves, leaves);
  }
}

function collectLeaves(value, prefix = "", result = new Map()) {
  if (typeof value === "string") {
    result.set(prefix, value);
    return result;
  }

  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new Error(`Invalid i18n value at ${prefix || "<root>"}; expected object or string.`);
  }

  for (const [key, child] of Object.entries(value)) {
    collectLeaves(child, prefix ? `${prefix}.${key}` : key, result);
  }

  return result;
}

function validateKeySet(locale, defaultLeaves, leaves) {
  const missing = [...defaultLeaves.keys()].filter((key) => !leaves.has(key));
  const extra = [...leaves.keys()].filter((key) => !defaultLeaves.has(key));
  if (missing.length > 0 || extra.length > 0) {
    const details = [
      missing.length > 0 ? `missing: ${missing.join(", ")}` : "",
      extra.length > 0 ? `extra: ${extra.join(", ")}` : "",
    ].filter(Boolean).join("; ");
    throw new Error(`Locale ${locale} keys do not match ${DEFAULT_LOCALE}: ${details}`);
  }
}

function validatePlaceholders(locale, defaultLeaves, leaves) {
  for (const [key, defaultValue] of defaultLeaves.entries()) {
    const expected = collectPlaceholders(defaultValue);
    const actual = collectPlaceholders(leaves.get(key));
    if (expected.join("\u0000") !== actual.join("\u0000")) {
      throw new Error(
        `Locale ${locale} placeholder mismatch at ${key}: expected {${expected.join(", ")}}, got {${actual.join(", ")}}`,
      );
    }
  }
}

function collectPlaceholders(value) {
  return [...String(value).matchAll(/\{(\w+)\}/gu)]
    .map((match) => match[1])
    .sort();
}
